# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Studio workflow package

"""Public Studio workflow facade for operator-facing project artifacts.

The studio package gathers workflow dataclasses and UI helper builders for
binding review, canvas artifacts, deployment readiness, export manifests,
runtime snapshots, live connector plans, and replay previews. Importing the
facade only exposes functions and types; concrete helpers own validation,
materialization planning, filesystem discovery, replay execution, and any live
connector records.
"""

from __future__ import annotations

from scpn_phase_orchestrator.studio.live_feed import (
    FEED_SCHEMA,
    RUNTIME_SCHEMA,
    STUDIO_ID,
    StudioFeedClaim,
    StudioFeedVerb,
    build_studio_control_feed,
    claim_summaries,
    render_studio_control_feed_json,
    runtime_summary,
)
from scpn_phase_orchestrator.studio.product import (
    STUDIO_REVIEW_PANEL_REGISTRY,
    build_studio_product_manifest,
)
from scpn_phase_orchestrator.studio.ui_helpers import (
    StudioKnobState,
    StudioReplayResult,
    apply_canvas_binding_rewrite_candidate,
    apply_knob_update,
    binding_spec_project_state,
    build_autopoietic_lineage_studio_panel,
    build_beginner_guidance,
    build_canvas_binding_rewrite_candidate,
    build_canvas_edit_artifact,
    build_canvas_graph,
    build_canvas_interaction_state,
    build_canvas_layout_manifest,
    build_canvas_topology_patch,
    build_command_table,
    build_deployment_package,
    build_deployment_readiness,
    build_error_report,
    build_evolutionary_supervisor_policy_search_studio_panel,
    build_export_manifests,
    build_hardware_target_package,
    build_hybrid_order_studio_panel,
    build_information_geometry_studio_panel,
    build_integrated_information_panel,
    build_intergenerational_inheritance_studio_panel,
    build_layer_table,
    build_live_connector_plan,
    build_live_connector_run_record,
    build_morphogenetic_field_studio_panel,
    build_multiverse_counterfactual_studio_panel,
    build_operator_checklist,
    build_oscillator_edit_artifact,
    build_oscillator_table,
    build_owned_live_connector_runtime_record,
    build_package_materialisation_plan,
    build_regime_chart_payload,
    build_runtime_snapshot,
    build_series_chart_payload,
    build_service_process_manifest,
    build_sheaf_cohomology_studio_panel,
    build_strange_loop_studio_panel,
    build_topos_semantic_binding_studio_panel,
    build_verified_hardware_target_package,
    disabled_export_reasons,
    discover_domainpacks,
    run_binding_spec_replay,
)
from scpn_phase_orchestrator.studio.workflow import (
    BindingProposal,
    ExportManifest,
    ImportedSourceSummary,
    RuntimeSnapshot,
    StudioProjectState,
)

__all__ = [
    "BindingProposal",
    "ExportManifest",
    "FEED_SCHEMA",
    "ImportedSourceSummary",
    "RUNTIME_SCHEMA",
    "RuntimeSnapshot",
    "STUDIO_ID",
    "StudioFeedClaim",
    "StudioFeedVerb",
    "StudioKnobState",
    "StudioProjectState",
    "StudioReplayResult",
    "STUDIO_REVIEW_PANEL_REGISTRY",
    "apply_canvas_binding_rewrite_candidate",
    "apply_knob_update",
    "binding_spec_project_state",
    "build_beginner_guidance",
    "build_canvas_edit_artifact",
    "build_canvas_binding_rewrite_candidate",
    "build_canvas_graph",
    "build_canvas_interaction_state",
    "build_canvas_layout_manifest",
    "build_canvas_topology_patch",
    "build_command_table",
    "build_deployment_package",
    "build_deployment_readiness",
    "build_error_report",
    "build_autopoietic_lineage_studio_panel",
    "build_intergenerational_inheritance_studio_panel",
    "build_studio_product_manifest",
    "build_evolutionary_supervisor_policy_search_studio_panel",
    "build_export_manifests",
    "build_hybrid_order_studio_panel",
    "build_information_geometry_studio_panel",
    "build_integrated_information_panel",
    "build_layer_table",
    "build_hardware_target_package",
    "build_live_connector_plan",
    "build_live_connector_run_record",
    "build_morphogenetic_field_studio_panel",
    "build_multiverse_counterfactual_studio_panel",
    "build_owned_live_connector_runtime_record",
    "build_operator_checklist",
    "build_oscillator_edit_artifact",
    "build_oscillator_table",
    "build_package_materialisation_plan",
    "build_regime_chart_payload",
    "build_runtime_snapshot",
    "build_series_chart_payload",
    "build_service_process_manifest",
    "build_studio_control_feed",
    "build_sheaf_cohomology_studio_panel",
    "build_strange_loop_studio_panel",
    "build_topos_semantic_binding_studio_panel",
    "build_verified_hardware_target_package",
    "claim_summaries",
    "disabled_export_reasons",
    "discover_domainpacks",
    "render_studio_control_feed_json",
    "run_binding_spec_replay",
    "runtime_summary",
]
