# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Tests for refresh_dependency_locks.py

"""Tests for ``tools/refresh_dependency_locks.py``.

The lock table is checked against the committed lockfiles themselves: every
generated lock under ``requirements/`` must be listed, and the command the tool
would run must equal the command recorded in that lock's header. Licence-block
preservation is exercised on the real committed bytes, and the CLI is run as a
subprocess.
"""

from __future__ import annotations

import importlib.util
import os
import runpy
import shlex
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "tools" / "refresh_dependency_locks.py"
REQUIREMENTS = ROOT / "requirements"


def _load() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "_refresh_dependency_locks_test_mod", SCRIPT
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


mod = _load()


def _recorded_command(path: Path) -> list[str]:
    """Return the generator command recorded in a committed lock header."""
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.removeprefix("#").strip()
        if stripped.startswith(("pip-compile ", "uv pip compile ")):
            return shlex.split(stripped)
    raise AssertionError(f"no generator command in {path.name}")


def _generated_lockfiles() -> set[str]:
    names = set()
    for path in REQUIREMENTS.glob("*.txt"):
        text = path.read_text(encoding="utf-8")
        if mod.PIP_COMPILE_HEADER in text or mod.UV_HEADER in text:
            names.add(path.name)
    return names


# ---------------------------------------------------------------------
# Lock table versus the committed lockfiles
# ---------------------------------------------------------------------


class TestLockTable:
    def test_every_generated_lock_is_listed_once(self) -> None:
        listed = [spec.name for spec in mod.LOCKS]
        assert len(listed) == len(set(listed))
        assert set(listed) == _generated_lockfiles()

    def test_hand_maintained_pin_lists_stay_outside_the_table(self) -> None:
        listed = {spec.name for spec in mod.LOCKS}
        for name in ("ci-tools.txt", "docs-tools.txt"):
            assert (REQUIREMENTS / name).is_file()
            assert name not in listed
            assert name not in _generated_lockfiles()

    @pytest.mark.parametrize("spec", mod.LOCKS, ids=lambda spec: spec.name)
    def test_command_matches_committed_header(self, spec: object) -> None:
        command = mod.build_command(spec, uvx="uvx", uv="uv")
        recorded = _recorded_command(ROOT / spec.output)
        if spec.generator == "uv":
            assert command == recorded
        else:
            # The pinned pip-tools release records ``--no-index`` in the header
            # next to ``--no-emit-index-url`` although the tool never passes it;
            # every lock regenerated by the tool therefore carries it.
            assert "--no-index" in recorded
            assert [part for part in recorded if part != "--no-index"] == [
                "pip-compile",
                *spec.arguments,
            ]
            assert command[-len(spec.arguments) :] == list(spec.arguments)

    @pytest.mark.parametrize("spec", mod.LOCKS, ids=lambda spec: spec.name)
    def test_header_interpreter_matches_table(self, spec: object) -> None:
        text = (ROOT / spec.output).read_text(encoding="utf-8")
        if spec.generator == "pip-compile":
            assert f"autogenerated by pip-compile with Python {spec.python}\n" in text
        else:
            assert ["--python-version", spec.python] == list(spec.arguments[2:4])

    @pytest.mark.parametrize("spec", mod.LOCKS, ids=lambda spec: spec.name)
    def test_every_input_is_committed_in_the_repository(self, spec: object) -> None:
        source = next(
            arg
            for arg in reversed(spec.arguments)
            if arg.endswith((".in", "pyproject.toml"))
        )
        assert not Path(source).is_absolute()
        assert (ROOT / source).is_file()

    def test_constraint_source_is_refreshed_before_its_consumers(self) -> None:
        order = [spec.output for spec in mod.LOCKS]
        dev = order.index("requirements/dev-lock.txt")
        for spec in mod.LOCKS:
            if "--constraint=requirements/dev-lock.txt" in spec.arguments:
                assert order.index(spec.output) > dev

    def test_pip_tools_version_is_documented(self) -> None:
        guide = (ROOT / "docs" / "guide" / "dependency_locks.md").read_text(
            encoding="utf-8"
        )
        assert f"pip-tools {mod.PIP_TOOLS_VERSION}" in guide

    def test_make_target_delegates_to_the_tool(self) -> None:
        makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
        recipe = makefile.split("\nlock-refresh:", 1)[1].split("\n\n", 1)[0]
        assert "tools/refresh_dependency_locks.py" in recipe
        assert "pip-compile " not in recipe


# ---------------------------------------------------------------------
# Licence-block preservation on real committed bytes
# ---------------------------------------------------------------------


class TestPreservedPrefix:
    def test_licence_block_before_pip_compile_header(self) -> None:
        text = (REQUIREMENTS / "runtime-lock.txt").read_text(encoding="utf-8")
        prefix = mod.preserved_prefix(text, "pip-compile")
        first_line = prefix.splitlines()[0]
        assert first_line.startswith("# SPDX-")
        assert first_line.endswith("AGPL-3.0-or-later")
        assert text[len(prefix) :].startswith("#\n" + mod.PIP_COMPILE_HEADER)

    def test_extra_separator_line_stays_in_the_prefix(self) -> None:
        text = (REQUIREMENTS / "audit-tools.txt").read_text(encoding="utf-8")
        prefix = mod.preserved_prefix(text, "pip-compile")
        assert prefix.endswith("dependency lock\n#\n")
        assert text[len(prefix) :].startswith("#\n" + mod.PIP_COMPILE_HEADER)

    def test_no_prefix_when_file_starts_with_the_generator_header(self) -> None:
        pip_text = (REQUIREMENTS / "dev-lock.txt").read_text(encoding="utf-8")
        uv_text = (REQUIREMENTS / "dev-lock-windows-ffi-py312.txt").read_text(
            encoding="utf-8"
        )
        assert mod.preserved_prefix(pip_text, "pip-compile") == ""
        assert mod.preserved_prefix(uv_text, "uv") == ""

    def test_missing_header_is_refused(self) -> None:
        text = (REQUIREMENTS / "docs-tools.txt").read_text(encoding="utf-8")
        with pytest.raises(ValueError, match="not found"):
            mod.preserved_prefix(text, "pip-compile")

    def test_pip_compile_header_without_opening_hash_is_refused(self) -> None:
        text = (REQUIREMENTS / "runtime-lock.txt").read_text(encoding="utf-8")
        broken = text.replace("#\n" + mod.PIP_COMPILE_HEADER, mod.PIP_COMPILE_HEADER)
        with pytest.raises(ValueError, match="opening"):
            mod.preserved_prefix(broken, "pip-compile")

    def test_header_on_first_line_without_opening_hash_is_refused(self) -> None:
        with pytest.raises(ValueError, match="opening"):
            mod.preserved_prefix(
                mod.PIP_COMPILE_HEADER + " with Python 3.12\n", "pip-compile"
            )

    @pytest.mark.parametrize(
        "name", ["runtime-lock.txt", "audit-tools.txt", "studio-sdk.txt"]
    )
    def test_restore_rebuilds_committed_bytes(self, name: str) -> None:
        text = (REQUIREMENTS / name).read_text(encoding="utf-8")
        prefix = mod.preserved_prefix(text, "pip-compile")
        regenerated = text[len(prefix) :]
        assert mod.restore_prefix(prefix, regenerated, "pip-compile") == text

    def test_restore_refuses_text_the_generator_does_not_own(self) -> None:
        text = (REQUIREMENTS / "runtime-lock.txt").read_text(encoding="utf-8")
        prefix = mod.preserved_prefix(text, "pip-compile")
        with pytest.raises(ValueError, match="does not start"):
            mod.restore_prefix(prefix, text, "pip-compile")


# ---------------------------------------------------------------------
# Command construction and selection
# ---------------------------------------------------------------------


class TestCommands:
    def test_pip_compile_runs_pinned_pip_tools_under_the_lock_interpreter(
        self,
    ) -> None:
        spec = mod.select_locks(["dev-lock-py313.txt"])[0]
        command = mod.build_command(spec, uvx="/bin/uvx", uv="/bin/uv")
        assert command[:6] == [
            "/bin/uvx",
            "--python",
            "3.13",
            "--from",
            f"pip-tools=={mod.PIP_TOOLS_VERSION}",
            "pip-compile",
        ]

    def test_windows_lock_uses_uv_for_the_windows_platform(self) -> None:
        spec = mod.select_locks(["dev-lock-windows-ffi-py311.txt"])[0]
        command = mod.build_command(spec, uvx="/bin/uvx", uv="/bin/uv")
        assert command[:5] == [
            "/bin/uv",
            "pip",
            "compile",
            "--python-platform",
            "windows",
        ]
        assert command[-2:] == ["-o", "requirements/dev-lock-windows-ffi-py311.txt"]

    def test_selection_keeps_canonical_order(self) -> None:
        selected = mod.select_locks(["studio-sdk.txt", "dev-lock.txt"])
        assert [spec.name for spec in selected] == ["dev-lock.txt", "studio-sdk.txt"]
        assert mod.select_locks([]) == mod.LOCKS

    def test_unknown_lock_name_is_refused(self) -> None:
        with pytest.raises(ValueError, match="unknown lockfile"):
            mod.select_locks(["dev-lock.txt", "not-a-lock.txt"])


# ---------------------------------------------------------------------
# In-place refresh with the committed bytes
# ---------------------------------------------------------------------


def _copy_lock(tmp_path: Path, name: str) -> tuple[Path, str]:
    target = tmp_path / "requirements" / name
    target.parent.mkdir(parents=True)
    text = (REQUIREMENTS / name).read_text(encoding="utf-8")
    target.write_text(text, encoding="utf-8")
    return target, text


class TestRefreshLock:
    def test_prefix_survives_a_generator_rewrite(self, tmp_path: Path) -> None:
        spec = mod.select_locks(["studio-sdk.txt"])[0]
        target, original = _copy_lock(tmp_path, spec.name)
        prefix = mod.preserved_prefix(original, "pip-compile")
        commands: list[list[str]] = []

        def rewrite_like_pip_compile(command: list[str], root: Path) -> None:
            commands.append(command)
            assert root == tmp_path
            target.write_text(original[len(prefix) :], encoding="utf-8")

        mod.refresh_lock(
            spec, tmp_path, uvx="uvx", uv="uv", runner=rewrite_like_pip_compile
        )
        assert target.read_text(encoding="utf-8") == original
        assert commands == [mod.build_command(spec, uvx="uvx", uv="uv")]

    def test_generator_failure_restores_committed_bytes(self, tmp_path: Path) -> None:
        spec = mod.select_locks(["runtime-lock.txt"])[0]
        target, original = _copy_lock(tmp_path, spec.name)

        def failing_generator(command: list[str], root: Path) -> None:
            target.write_text("partial output\n", encoding="utf-8")
            raise subprocess.CalledProcessError(1, command)

        with pytest.raises(subprocess.CalledProcessError):
            mod.refresh_lock(
                spec, tmp_path, uvx="uvx", uv="uv", runner=failing_generator
            )
        assert target.read_text(encoding="utf-8") == original

    def test_foreign_leading_text_is_refused_and_rolled_back(
        self, tmp_path: Path
    ) -> None:
        spec = mod.select_locks(["runtime-lock.txt"])[0]
        target, original = _copy_lock(tmp_path, spec.name)

        def untouched_generator(command: list[str], root: Path) -> None:
            return None

        with pytest.raises(ValueError, match="does not start"):
            mod.refresh_lock(
                spec, tmp_path, uvx="uvx", uv="uv", runner=untouched_generator
            )
        assert target.read_text(encoding="utf-8") == original

    def test_default_runner_executes_in_the_repository_root(
        self, tmp_path: Path
    ) -> None:
        marker = tmp_path / "ran-here"
        mod._run([sys.executable, "-c", "open('ran-here', 'w').close()"], tmp_path)
        assert marker.is_file()


# ---------------------------------------------------------------------
# Command-line interface
# ---------------------------------------------------------------------


def _cli(
    *args: str, env: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )


class TestCli:
    def test_list_names_every_lock_with_its_interpreter(self) -> None:
        result = _cli("--list")
        assert result.returncode == 0
        lines = result.stdout.splitlines()
        assert len(lines) == len(mod.LOCKS)
        assert "requirements/dev-lock-py311.txt\tpip-compile\tpython 3.11" in lines

    def test_dry_run_prints_commands_without_touching_files(self) -> None:
        before = (REQUIREMENTS / "pqc-lock.txt").read_bytes()
        result = _cli("--dry-run", "--only", "pqc-lock.txt")
        assert result.returncode == 0
        assert result.stdout.strip() == " ".join(
            mod.build_command(mod.select_locks(["pqc-lock.txt"])[0], uvx="uvx", uv="uv")
        )
        assert (REQUIREMENTS / "pqc-lock.txt").read_bytes() == before

    def test_unknown_lock_exits_with_usage_status(self) -> None:
        result = _cli("--only", "missing.txt")
        assert result.returncode == 2
        assert "unknown lockfile(s): missing.txt" in result.stderr

    def test_missing_uvx_stops_before_any_generator_runs(self, tmp_path: Path) -> None:
        env = dict(os.environ)
        env["PATH"] = str(tmp_path)
        before = (REQUIREMENTS / "pqc-lock.txt").read_bytes()
        result = _cli("--only", "pqc-lock.txt", env=env)
        assert result.returncode == 1
        assert "uvx is required on PATH" in result.stderr
        assert (REQUIREMENTS / "pqc-lock.txt").read_bytes() == before

    def test_in_process_list_and_dry_run(
        self, capsys: pytest.CaptureFixture[str]
    ) -> None:
        assert mod.main(["--list", "--only", "mojo-lock.txt"]) == 0
        assert capsys.readouterr().out == (
            "requirements/mojo-lock.txt\tpip-compile\tpython 3.12\n"
        )
        assert mod.main(["--dry-run", "--only", "dev-lock-windows-ffi-py312.txt"]) == 0
        printed = capsys.readouterr().out.strip()
        assert printed.startswith("uv pip compile --python-platform windows")

    def test_in_process_unknown_lock_returns_usage_status(
        self, capsys: pytest.CaptureFixture[str]
    ) -> None:
        assert mod.main(["--only", "missing.txt"]) == 2
        assert "unknown lockfile(s): missing.txt" in capsys.readouterr().err

    def test_executable_lookup_uses_path(self) -> None:
        assert Path(mod._executable(Path(sys.executable).name)).is_file()
        with pytest.raises(SystemExit, match="is required on PATH"):
            mod._executable("spo-no-such-executable-for-lock-refresh")

    def test_script_entry_point_exits_with_main_status(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        monkeypatch.setattr(sys, "argv", [str(SCRIPT), "--list"])
        with pytest.raises(SystemExit) as excinfo:
            runpy.run_path(str(SCRIPT), run_name="__main__")
        assert excinfo.value.code == 0

    def test_main_refreshes_selected_locks_in_order(
        self, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls: list[tuple[str, bool]] = []
        monkeypatch.setattr(mod, "_executable", lambda name: f"/opt/{name}")

        def record(
            spec: object, root: Path, *, uvx: str, uv: str, upgrade: bool
        ) -> None:
            assert (root, uvx, uv) == (mod.ROOT, "/opt/uvx", "/opt/uv")
            calls.append((spec.name, upgrade))

        monkeypatch.setattr(mod, "refresh_lock", record)
        assert mod.main(["--only", "julia-lock.txt", "--only", "dev-lock.txt"]) == 0
        assert calls == [("dev-lock.txt", False), ("julia-lock.txt", False)]
        calls.clear()
        assert mod.main(["--upgrade", "--only", "pqc-lock.txt"]) == 0
        assert calls == [("pqc-lock.txt", True)]


class TestUpgrade:
    @pytest.mark.parametrize("spec", mod.LOCKS, ids=lambda spec: spec.name)
    def test_upgrade_adds_only_the_flag_before_the_recorded_arguments(
        self, spec: object
    ) -> None:
        plain = mod.build_command(spec, uvx="uvx", uv="uv")
        upgraded = mod.build_command(spec, uvx="uvx", uv="uv", upgrade=True)
        index = len(plain) - len(spec.arguments)
        assert upgraded == [*plain[:index], "--upgrade", *plain[index:]]

    def test_dry_run_shows_the_upgrade_flag(
        self, capsys: pytest.CaptureFixture[str]
    ) -> None:
        assert mod.main(["--dry-run", "--upgrade", "--only", "pqc-lock.txt"]) == 0
        printed = capsys.readouterr().out.split()
        assert printed[printed.index("pip-compile") + 1] == "--upgrade"

    def test_refresh_lock_forwards_upgrade_to_the_generator(
        self, tmp_path: Path
    ) -> None:
        spec = mod.select_locks(["runtime-lock.txt"])[0]
        target, original = _copy_lock(tmp_path, spec.name)
        prefix = mod.preserved_prefix(original, "pip-compile")
        commands: list[list[str]] = []

        def rewrite(command: list[str], root: Path) -> None:
            commands.append(command)
            target.write_text(original[len(prefix) :], encoding="utf-8")

        mod.refresh_lock(
            spec, tmp_path, uvx="uvx", uv="uv", upgrade=True, runner=rewrite
        )
        assert "--upgrade" in commands[0]
        assert target.read_text(encoding="utf-8") == original
