# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Native sheaf integration contracts

"""Exercise the installed sheaf boundary without substituting a native producer."""

from __future__ import annotations

import inspect

import numpy as np
import pytest
import spo_kernel
from scipy.integrate import solve_ivp

from scpn_phase_orchestrator import SheafUPDEEngine


def test_native_keyword_and_documented_defaults_advance_real_state() -> None:
    """Documented defaults and keyword controls produce exact elapsed intervals.

    Every handwritten binding is exercised here or by the buffer and batch
    cases. The extra uncovered function at #[pymethods] is generated by PyO3;
    it has no separate handwritten entry point that a real call can select.
    """
    signature = inspect.signature(spo_kernel.PySheafUPDEStepper)
    assert signature.parameters["dt"].default == 0.01
    assert signature.parameters["n_substeps"].default == 1
    assert signature.parameters["atol"].default == 1e-6
    assert signature.parameters["rtol"].default == 1e-3
    phase = np.array([0.2])
    frequency = np.array([1.0])
    maps = np.zeros(1)
    target = np.zeros(1)
    default = spo_kernel.PySheafUPDEStepper(n=1, d=1)
    configured = spo_kernel.PySheafUPDEStepper(
        n=1, d=1, dt=0.02, method="rk45", n_substeps=3, atol=1e-10, rtol=1e-10
    )
    np.testing.assert_allclose(
        default.run(phase, frequency, maps, 0.0, target, 3), [0.23], atol=1e-15
    )
    np.testing.assert_allclose(
        configured.run(phase, frequency, maps, 0.0, target, 3), [0.26], atol=1e-15
    )
    np.testing.assert_array_equal(phase, [0.2])


@pytest.mark.parametrize("method", ["euler", "rk4", "rk45"])
@pytest.mark.parametrize("substeps", [1, 3])
@pytest.mark.parametrize("operation", ["step", "run"])
def test_native_methods_advance_configured_horizon(
    method: str, substeps: int, operation: str
) -> None:
    """Native geometry and substeps preserve exact uncoupled elapsed time."""
    native = spo_kernel.PySheafUPDEStepper(2, 2, 0.01, method, substeps)
    phases = np.array([0.2, 0.5, 0.8, 1.1])
    omegas = np.array([1.0, -0.5, 0.8, 1.2])
    maps = np.zeros(16)
    psi = np.zeros(2)
    steps = 1 if operation == "step" else 7
    output = (
        native.step(phases, omegas, maps, 0.0, psi)
        if operation == "step"
        else native.run(phases, omegas, maps, 0.0, psi, steps)
    )
    np.testing.assert_allclose(
        output, phases + steps * 0.01 * omegas, atol=2e-15, rtol=0
    )
    assert native.n == 2 and native.d == 2
    assert 0.0 < native.last_dt <= 0.01
    assert output.dtype == np.float64 and output.shape == (4,)
    assert not np.shares_memory(output, phases)
    np.testing.assert_array_equal(phases, [0.2, 0.5, 0.8, 1.1])


@pytest.mark.parametrize("method", ["euler", "rk4", "rk45"])
@pytest.mark.parametrize("operation", ["step", "run"])
def test_native_shared_readonly_inputs_follow_entry_equation(
    method: str, operation: str
) -> None:
    """Aliased readonly phase, frequency, map and target buffers remain unchanged."""
    shared = np.array([0.4])
    shared.setflags(write=False)
    native = spo_kernel.PySheafUPDEStepper(1, 1, 0.01, method)
    output = (
        native.step(shared, shared, shared, 0.0, shared)
        if operation == "step"
        else native.run(shared, shared, shared, 0.0, shared, 5)
    )
    # N=D=1 map couples a phase to itself, so the exact derivative is omega.
    np.testing.assert_allclose(
        output, [0.404 if operation == "step" else 0.42], atol=1e-15, rtol=0
    )
    np.testing.assert_array_equal(shared, [0.4])
    assert not np.shares_memory(output, shared)


@pytest.mark.parametrize("field", ["phases", "omegas", "maps", "psi"])
@pytest.mark.parametrize("fault", ["short", "nonfinite", "strided", "dtype", "matrix"])
@pytest.mark.parametrize("operation", ["step", "run", "zero"])
def test_native_buffer_refusal_preserves_solver_and_recovers(
    field: str, fault: str, operation: str
) -> None:
    """Real malformed buffers refuse even zero batches; the same solver recovers."""
    buffers = {
        "phases": np.array([0.1, 0.2, 0.3, 0.4]),
        "omegas": np.ones(4),
        "maps": np.zeros(16),
        "psi": np.zeros(2),
    }
    saved = {name: values.copy() for name, values in buffers.items()}
    invalid = buffers[field].copy()
    if fault == "short":
        invalid = invalid[:-1]
    elif fault == "nonfinite":
        invalid[0] = np.inf
    elif fault == "strided":
        storage = np.repeat(invalid, 2)
        invalid = storage[::2]
    elif fault == "matrix":
        invalid = invalid.reshape(1, -1)
    else:
        invalid = invalid.astype(np.float32)
    buffers[field] = invalid
    native = spo_kernel.PySheafUPDEStepper(2, 2, 0.01, "rk45")
    expected_error = TypeError if fault in ("dtype", "matrix") else ValueError
    with pytest.raises(expected_error):
        if operation == "step":
            native.step(
                buffers["phases"],
                buffers["omegas"],
                buffers["maps"],
                0.0,
                buffers["psi"],
            )
        else:
            native.run(
                buffers["phases"],
                buffers["omegas"],
                buffers["maps"],
                0.0,
                buffers["psi"],
                0 if operation == "zero" else 2,
            )
    assert native.last_dt == 0.01
    buffers = saved
    output = native.run(
        buffers["phases"], buffers["omegas"], buffers["maps"], 0.0, buffers["psi"], 2
    )
    np.testing.assert_allclose(output, [0.12, 0.22, 0.32, 0.42], atol=1e-15, rtol=0)
    np.testing.assert_array_equal(saved["phases"], [0.1, 0.2, 0.3, 0.4])


@pytest.mark.parametrize("field", ["n", "d", "n_substeps", "dt", "atol", "rtol"])
@pytest.mark.parametrize(
    "value", [True, "1", np.bool_(True), np.timedelta64(1, "s"), 1 + 0j]
)
def test_native_constructor_refuses_original_type_aliases(
    field: str, value: object
) -> None:
    """Source types remain visible before native count/scalar coercion."""
    kwargs: dict[str, object] = {"n": 2, "d": 2}
    kwargs[field] = value
    with pytest.raises(ValueError):
        spo_kernel.PySheafUPDEStepper(**kwargs)


@pytest.mark.parametrize(
    ("kwargs", "expected_error"),
    [
        ({"n": 0}, ValueError),
        ({"d": 0}, ValueError),
        ({"n": -1}, OverflowError),
        ({"d": 2**64 - 1}, ValueError),
        ({"n_substeps": 0}, ValueError),
        ({"n_substeps": 2**32}, ValueError),
        ({"dt": 0.0}, ValueError),
        ({"dt": np.inf}, ValueError),
        ({"atol": 0.0}, ValueError),
        ({"rtol": np.nan}, ValueError),
        ({"method": "heun"}, ValueError),
        ({"method": "rk45", "atol": 1e-2, "rtol": 1e-3}, ValueError),
        ({"dt": np.nextafter(0.0, 1.0), "n_substeps": 2}, ValueError),
        ({"method": False}, TypeError),
        ({"method": 1}, TypeError),
        ({"n": 2**64}, OverflowError),
        ({"d": -1}, OverflowError),
        ({"n_substeps": -1}, OverflowError),
    ],
)
def test_native_constructor_refuses_unusable_geometry_and_controls(
    kwargs: dict[str, object],
    expected_error: type[Exception],
) -> None:
    """Invalid shape products and unrepresentable substeps refuse before allocation."""
    controls: dict[str, object] = {"n": 2, "d": 2}
    controls.update(kwargs)
    with pytest.raises(expected_error):
        spo_kernel.PySheafUPDEStepper(**controls)


@pytest.mark.parametrize(
    ("value", "expected_error"),
    [
        (True, ValueError),
        ("1", ValueError),
        (-1, OverflowError),
        (1.5, ValueError),
        (np.bool_(True), ValueError),
        (2**64, OverflowError),
    ],
)
def test_native_batch_refuses_count_aliases(
    value: object, expected_error: type[Exception]
) -> None:
    """A batch count refuses aliases without consuming solver state."""
    native = spo_kernel.PySheafUPDEStepper(1, 1)
    phase = np.array([0.2])
    with pytest.raises(expected_error):
        native.run(phase, np.ones(1), np.zeros(1), 0.0, np.zeros(1), value)
    np.testing.assert_allclose(
        native.run(phase, np.ones(1), np.zeros(1), 0.0, np.zeros(1), 1),
        [0.21],
        atol=1e-15,
    )


@pytest.mark.parametrize("value", [True, "0.1", np.bool_(True), np.inf, 10**400])
def test_native_drive_refuses_aliases_and_nonfinite_values(value: object) -> None:
    """Original drive types and unrepresentable values cannot enter the equation."""
    native = spo_kernel.PySheafUPDEStepper(1, 1)
    phase = np.zeros(1)
    with pytest.raises(ValueError):
        native.step(phase, np.ones(1), np.zeros(1), value, np.zeros(1))
    assert native.last_dt == 0.01
    np.testing.assert_array_equal(phase, [0.0])


def test_native_zero_batch_returns_independent_unwrapped_copy() -> None:
    """Zero steps preserve valid finite input phases without integration or wrapping."""
    native = spo_kernel.PySheafUPDEStepper(
        n=np.int64(1), d=np.int64(1), dt=np.float64(0.01)
    )
    phase = np.array([-0.4])
    output = native.run(
        phase, np.ones(1), np.zeros(1), np.float64(0.0), np.zeros(1), np.int64(0)
    )
    np.testing.assert_array_equal(output, phase)
    assert not np.shares_memory(output, phase)
    assert native.last_dt == 0.01


@pytest.mark.parametrize("method", ["euler", "rk4", "rk45"])
@pytest.mark.parametrize("operation", ["step", "run"])
def test_native_numerical_refusal_recovers_on_same_instance(
    method: str, operation: str
) -> None:
    """Nonfinite output refusal preserves the complete call's timestep and input.

    Native adaptive proposals are capped by finite positive configured dt
    after a finite clamped factor, so the non-finite proposal arm is unreachable.
    Public subnormal-interval cases exercise actual zero-proposal refusal;
    these native overflow cases exercise producer refusal and recovery.
    """
    native = spo_kernel.PySheafUPDEStepper(1, 1, 10.0, method)
    phase = np.zeros(1)
    huge = np.full(1, 1e308)
    with pytest.raises(ValueError):
        if operation == "step":
            native.step(phase, huge, np.zeros(1), 0.0, np.zeros(1))
        else:
            native.run(phase, huge, np.zeros(1), 0.0, np.zeros(1), 2)
    assert native.last_dt == 10.0
    np.testing.assert_array_equal(phase, [0.0])
    np.testing.assert_allclose(
        native.run(phase, np.full(1, 0.1), np.zeros(1), 0.0, np.zeros(1), 2),
        [2.0],
        atol=1e-14,
        rtol=0,
    )


@pytest.mark.parametrize("method", ["euler", "rk4", "rk45"])
@pytest.mark.parametrize("operation", ["step", "run"])
@pytest.mark.parametrize(
    ("phase_value", "omega"),
    [(-1e-300, 0.0), (0.0, -1e-15), (-2 * np.pi, 0.0), (-4 * np.pi, 0.0)],
)
def test_native_torus_rounding_and_negative_crossings_return_zero(
    method: str, operation: str, phase_value: float, omega: float
) -> None:
    """Negative crossings and exact torus multiples return positive zero.

    After '%' and conditional addition, finite values are nonnegative and
    the rounded upper endpoint is mapped to zero. Thus the final native
    negative/upper-endpoint guards cannot fail with admitted real input.
    These cases cover the nearest producer behavior without a fake output.
    """
    native = spo_kernel.PySheafUPDEStepper(1, 1, 0.01, method)
    phase = np.array([phase_value])
    frequency = np.array([omega])
    output = (
        native.step(phase, frequency, np.zeros(1), 0.0, np.zeros(1))
        if operation == "step"
        else native.run(phase, frequency, np.zeros(1), 0.0, np.zeros(1), 3)
    )
    np.testing.assert_array_equal(output, [0.0])
    assert not np.any(np.signbit(output))
    np.testing.assert_array_equal(phase, [phase_value])


@pytest.mark.parametrize("method", ["euler", "rk4", "rk45"])
def test_public_uses_installed_native_class_and_matching_equation(method: str) -> None:
    """Public matrix dispatch preserves real native anisotropic forcing."""
    public = SheafUPDEEngine(2, 2, 0.01, method=method)
    assert isinstance(public._rust, spo_kernel.PySheafUPDEStepper)
    phases = np.array([[0.1, 0.4], [0.9, 1.2]])
    frequencies = np.array([[0.2, -0.1], [0.05, 0.15]])
    maps = np.zeros((2, 2, 2, 2))
    maps[0, 1] = [[0.3, 0.1], [0.2, 0.4]]
    maps[1, 0] = [[0.5, 0.0], [0.1, 0.2]]
    psi = np.array([0.7, 1.0])
    direct = spo_kernel.PySheafUPDEStepper(2, 2, 0.01, method)
    output = public.run(phases, frequencies, maps, 0.2, psi, 5)
    native = direct.run(phases.ravel(), frequencies.ravel(), maps.ravel(), 0.2, psi, 5)
    np.testing.assert_allclose(output.ravel(), native, atol=1e-15, rtol=0)
    np.testing.assert_array_equal(phases, [[0.1, 0.4], [0.9, 1.2]])


def test_native_adaptive_full_horizon_matches_nonlinear_reference() -> None:
    """Repeated forced RK45 intervals agree with an independent high-order solver."""
    native = spo_kernel.PySheafUPDEStepper(1, 1, 0.4, "rk45", atol=1e-12, rtol=1e-12)
    phase = np.array([0.1])
    frequency = np.array([0.3])
    maps = np.zeros(1)
    psi = np.array([1.2])
    reference = solve_ivp(
        lambda _t, y: 0.3 + 2.0 * np.sin(1.2 - y),
        (0.0, 2.0),
        phase,
        method="DOP853",
        atol=1e-13,
        rtol=1e-13,
    ).y[:, -1]
    output = native.run(phase, frequency, maps, 2.0, psi, 5)
    np.testing.assert_allclose(output, reference, atol=2e-11, rtol=0)
    assert 0.0 < native.last_dt < 0.4


def test_native_tiny_configured_interval_is_not_silently_ignored() -> None:
    """A positive interval below the former absolute loop cutoff still advances."""
    native = spo_kernel.PySheafUPDEStepper(1, 1, 1e-14, "rk45")
    output = native.run(np.zeros(1), np.ones(1), np.zeros(1), 0.0, np.zeros(1), 3)
    np.testing.assert_allclose(output, [3e-14], atol=1e-28, rtol=0)
