# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Reactor semantic public facade

"""Reactor-family-neutral phase semantics and regime evidence.

This facade is non-actuating. It describes reactor context, observations,
semantic carriers, compatible relations, and review-only regime estimates.
"""

from .contracts import (
    JsonValue,
    ObservableDescriptor,
    PhaseRelation,
    PhaseSemanticRecord,
    ReactorContext,
    RegimeAxis,
    RegimeEstimate,
    build_phase_relation,
    validate_observable_sequence,
)
from .coupled_transport import (
    FUSION_COUPLED_TRANSPORT_SCHEMA,
    FUSION_TORAX_OUTCOME_SCHEMA,
    FUSION_TORAX_REVIEW_SCHEMA,
    coupled_transport_handoff_from_fusion_bytes,
)
from .evidence import (
    CalibrationReference,
    ClockReference,
    ProvenanceRecord,
    QualityAssessment,
    Uncertainty,
    ValidityWindow,
)
from .handoff import (
    HANDOFF_SCHEMA,
    HANDOFF_SCHEMA_VERSION,
    MAX_HANDOFF_JSON_BYTES,
    MAX_SOURCE_ENVELOPE_BYTES,
    ReactorSemanticHandoff,
    canonicalize_source_envelope,
    handoff_digest,
    handoff_from_bytes,
    handoff_from_json,
    handoff_from_record,
    handoff_to_bytes,
    handoff_to_json,
    handoff_to_record,
)
from .mif_merge_compression import (
    MAX_MIF_MERGE_COMPRESSION_HANDOFF_BYTES,
    MIF_MERGE_COMPRESSION_HANDOFF_SCHEMA,
    MIF_MERGE_COMPRESSION_HANDOFF_VERSION,
    MIF_MERGE_COMPRESSION_SOURCE_SCHEMA,
    MIF_MERGE_COMPRESSION_SOURCE_VERSION,
    MIFMergeCompressionHandoff,
    mif_merge_compression_handoff_digest,
    mif_merge_compression_handoff_from_bytes,
    mif_merge_compression_handoff_from_mif_bytes,
    mif_merge_compression_handoff_from_record,
    mif_merge_compression_handoff_to_bytes,
    mif_merge_compression_handoff_to_record,
)
from .observability_profiles import (
    DEFAULT_REACTOR_OBSERVABILITY_PROFILE_REGISTRY,
    REACTOR_OBSERVABILITY_PROFILE_REGISTRY_VERSION,
    ObservabilityClass,
    ReactorObservabilityProfileRegistry,
    ReactorSignalCandidateProfile,
    UnmetEvidenceDisposition,
)
from .reference_portfolio import (
    ReactorReferenceSlice,
    build_reactor_reference_portfolio,
)
from .regime_ontology import (
    DEFAULT_REACTOR_REGIME_MODE_ONTOLOGY,
    REACTOR_REGIME_MODE_ONTOLOGY_VERSION,
    AxisApplicability,
    AxisApplicabilityPolicy,
    ModeDomain,
    ReactorModeBinding,
    ReactorModeDefinition,
    ReactorRegimeAxisAssignment,
    ReactorRegimeAxisDefinition,
    ReactorRegimeModeOntologyRegistry,
)
from .registry import (
    DEFAULT_REACTOR_REGISTRY,
    REACTOR_REGISTRY_VERSION,
    ReactorConfiguration,
    ReactorConfigurationRegistry,
)
from .semantic_profiles import (
    DEFAULT_REACTOR_SEMANTIC_PROFILE_REGISTRY,
    REACTOR_FAMILY_ASSIGNMENT_MAP_SHA256,
    REACTOR_SEMANTIC_PROFILE_REGISTRY_VERSION,
    ReactorSemanticProfile,
    ReactorSemanticProfileRegistry,
    SemanticIngressState,
)
from .serialization import (
    ReactorSemanticContract,
    canonical_json,
    contract_digest,
    contract_from_json,
    contract_from_record,
    contract_to_record,
)
from .vocabulary import (
    ACTION_OWNER,
    PLANT_TRUTH_OWNERS,
    REVIEW_ONLY_AUTHORITY,
    SEMANTIC_OWNER,
    U0_SCHEMA_VERSION,
    ClockKind,
    ConfinementFamily,
    ConversionKind,
    DriverKind,
    EvidenceClass,
    OperatingCadence,
    PhaseRelationType,
    QualityState,
    ReactionKind,
    RegimeState,
    RelationInterpretation,
    SemanticCarrier,
    ValidityState,
)

__all__ = [
    "ACTION_OWNER",
    "DEFAULT_REACTOR_OBSERVABILITY_PROFILE_REGISTRY",
    "DEFAULT_REACTOR_REGIME_MODE_ONTOLOGY",
    "DEFAULT_REACTOR_REGISTRY",
    "DEFAULT_REACTOR_SEMANTIC_PROFILE_REGISTRY",
    "HANDOFF_SCHEMA",
    "HANDOFF_SCHEMA_VERSION",
    "MAX_HANDOFF_JSON_BYTES",
    "MAX_MIF_MERGE_COMPRESSION_HANDOFF_BYTES",
    "MAX_SOURCE_ENVELOPE_BYTES",
    "PLANT_TRUTH_OWNERS",
    "REACTOR_OBSERVABILITY_PROFILE_REGISTRY_VERSION",
    "REACTOR_REGIME_MODE_ONTOLOGY_VERSION",
    "REACTOR_REGISTRY_VERSION",
    "REACTOR_FAMILY_ASSIGNMENT_MAP_SHA256",
    "REACTOR_SEMANTIC_PROFILE_REGISTRY_VERSION",
    "REVIEW_ONLY_AUTHORITY",
    "SEMANTIC_OWNER",
    "U0_SCHEMA_VERSION",
    "CalibrationReference",
    "AxisApplicability",
    "AxisApplicabilityPolicy",
    "ClockKind",
    "ClockReference",
    "ConfinementFamily",
    "ConversionKind",
    "DriverKind",
    "EvidenceClass",
    "FUSION_COUPLED_TRANSPORT_SCHEMA",
    "FUSION_TORAX_OUTCOME_SCHEMA",
    "FUSION_TORAX_REVIEW_SCHEMA",
    "JsonValue",
    "MIFMergeCompressionHandoff",
    "MIF_MERGE_COMPRESSION_HANDOFF_SCHEMA",
    "MIF_MERGE_COMPRESSION_HANDOFF_VERSION",
    "MIF_MERGE_COMPRESSION_SOURCE_SCHEMA",
    "MIF_MERGE_COMPRESSION_SOURCE_VERSION",
    "ModeDomain",
    "ObservableDescriptor",
    "ObservabilityClass",
    "OperatingCadence",
    "PhaseRelation",
    "PhaseRelationType",
    "PhaseSemanticRecord",
    "ProvenanceRecord",
    "QualityAssessment",
    "QualityState",
    "ReactionKind",
    "ReactorConfiguration",
    "ReactorConfigurationRegistry",
    "ReactorContext",
    "ReactorModeBinding",
    "ReactorModeDefinition",
    "ReactorObservabilityProfileRegistry",
    "ReactorReferenceSlice",
    "ReactorSemanticContract",
    "ReactorSemanticHandoff",
    "ReactorSemanticProfile",
    "ReactorSemanticProfileRegistry",
    "ReactorSignalCandidateProfile",
    "ReactorRegimeAxisAssignment",
    "ReactorRegimeAxisDefinition",
    "ReactorRegimeModeOntologyRegistry",
    "RegimeAxis",
    "RegimeEstimate",
    "RegimeState",
    "RelationInterpretation",
    "SemanticCarrier",
    "SemanticIngressState",
    "Uncertainty",
    "UnmetEvidenceDisposition",
    "ValidityState",
    "ValidityWindow",
    "build_phase_relation",
    "build_reactor_reference_portfolio",
    "canonical_json",
    "canonicalize_source_envelope",
    "contract_digest",
    "contract_from_json",
    "contract_from_record",
    "contract_to_record",
    "coupled_transport_handoff_from_fusion_bytes",
    "handoff_digest",
    "handoff_from_bytes",
    "handoff_from_json",
    "handoff_from_record",
    "handoff_to_bytes",
    "handoff_to_json",
    "handoff_to_record",
    "mif_merge_compression_handoff_digest",
    "mif_merge_compression_handoff_from_bytes",
    "mif_merge_compression_handoff_from_mif_bytes",
    "mif_merge_compression_handoff_from_record",
    "mif_merge_compression_handoff_to_bytes",
    "mif_merge_compression_handoff_to_record",
    "validate_observable_sequence",
]
