# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tspo.proto\x12\x03spo\"\x0e\n\x0cStateRequest\"\x1e\n\x0bStepRequest\x12\x0f\n\x07n_steps\x18\x01 \x01(\x05\"\x0e\n\x0cResetRequest\"6\n\rStreamRequest\x12\x11\n\tmax_steps\x18\x01 \x01(\x05\x12\x12\n\ninterval_s\x18\x02 \x01(\x01\"\x0f\n\rConfigRequest\"2\n\nLayerState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01R\x18\x02 \x01(\x01\x12\x0b\n\x03psi\x18\x03 \x01(\x01\"\x90\x01\n\rStateResponse\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x10\n\x08R_global\x18\x02 \x01(\x01\x12\x0e\n\x06regime\x18\x03 \x01(\t\x12\x16\n\x0e\x61mplitude_mode\x18\x04 \x01(\x08\x12\x16\n\x0emean_amplitude\x18\x05 \x01(\x01\x12\x1f\n\x06layers\x18\x06 \x03(\x0b\x32\x0f.spo.LayerState\"\x92\x01\n\x0e\x43onfigResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rn_oscillators\x18\x02 \x01(\x05\x12\x10\n\x08n_layers\x18\x03 \x01(\x05\x12\x16\n\x0e\x61mplitude_mode\x18\x04 \x01(\x08\x12\x17\n\x0fsample_period_s\x18\x05 \x01(\x01\x12\x18\n\x10\x63ontrol_period_s\x18\x06 \x01(\x01\x32\x94\x02\n\x11PhaseOrchestrator\x12\x31\n\x08GetState\x12\x11.spo.StateRequest\x1a\x12.spo.StateResponse\x12,\n\x04Step\x12\x10.spo.StepRequest\x1a\x12.spo.StateResponse\x12.\n\x05Reset\x12\x11.spo.ResetRequest\x1a\x12.spo.StateResponse\x12\x38\n\x0cStreamPhases\x12\x12.spo.StreamRequest\x1a\x12.spo.StateResponse0\x01\x12\x34\n\tGetConfig\x12\x12.spo.ConfigRequest\x1a\x13.spo.ConfigResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATEREQUEST']._serialized_start=18
  _globals['_STATEREQUEST']._serialized_end=32
  _globals['_STEPREQUEST']._serialized_start=34
  _globals['_STEPREQUEST']._serialized_end=64
  _globals['_RESETREQUEST']._serialized_start=66
  _globals['_RESETREQUEST']._serialized_end=80
  _globals['_STREAMREQUEST']._serialized_start=82
  _globals['_STREAMREQUEST']._serialized_end=136
  _globals['_CONFIGREQUEST']._serialized_start=138
  _globals['_CONFIGREQUEST']._serialized_end=153
  _globals['_LAYERSTATE']._serialized_start=155
  _globals['_LAYERSTATE']._serialized_end=205
  _globals['_STATERESPONSE']._serialized_start=208
  _globals['_STATERESPONSE']._serialized_end=352
  _globals['_CONFIGRESPONSE']._serialized_start=355
  _globals['_CONFIGRESPONSE']._serialized_end=501
  _globals['_PHASEORCHESTRATOR']._serialized_start=504
  _globals['_PHASEORCHESTRATOR']._serialized_end=780
# @@protoc_insertion_point(module_scope)
