# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — HDL Synthesis Compiler

"""Kuramoto topology to synthesisable Verilog.

Translates a learned coupling matrix ``K_nm`` and natural-frequency vector
``omega`` into a fixed-point Verilog module that can be compiled by standard
FPGA toolchains (Vivado, Quartus). The emitted design instantiates the
shared ``cordic_sincos`` primitive from
``spo-kernel/crates/spo-fpga/src/kuramoto_core.v`` for every non-zero
``K_ij`` entry and performs Euler integration in Q16.16 fixed-point.

The compiler is arithmetic-complete — no ``real``, no system tasks, no
``$sin`` — so its output is synthesisable rather than simulation-only.
"""

from __future__ import annotations

from numpy.typing import NDArray

__all__ = ["KuramotoVerilogCompiler"]

# Q16.16 fixed-point configuration.
_FRAC_BITS = 16
_WORD_BITS = 32
_Q_SCALE = 1 << _FRAC_BITS
_Q_MASK = (1 << _WORD_BITS) - 1


def _q16_16(value: float) -> int:
    """Convert a Python float to Q16.16 two's-complement bit pattern.

    Saturates to the representable range rather than wrapping silently.
    """
    scaled = round(value * _Q_SCALE)
    lo = -(1 << (_WORD_BITS - 1))
    hi = (1 << (_WORD_BITS - 1)) - 1
    if scaled < lo:
        scaled = lo
    elif scaled > hi:
        scaled = hi
    return scaled & _Q_MASK


def _hex_q16_16(value: float) -> str:
    """Format a float as a Verilog ``32'hXXXXXXXX`` Q16.16 constant."""
    return f"32'h{_q16_16(value):08X}"


class KuramotoVerilogCompiler:
    """Compile a Kuramoto topology into synthesisable Verilog.

    Each oscillator becomes a Q16.16 state register driven by Euler
    integration of

        dθ_i/dt = ω_i + Σ_j K_ij · sin(θ_j − θ_i)

    where the sin() primitive is the ``cordic_sincos`` pipelined CORDIC
    from the FPGA kuramoto_core library. Only non-zero coupling entries
    materialise in hardware.

    Parameters
    ----------
    n_oscillators:
        Size of the mesh; matches the rows/columns of the coupling matrix.
    bit_width:
        Data width in bits (default 32 for Q16.16).
    cordic_stages:
        Number of CORDIC rotation stages (default 4). Must match the
        parameter used on the instantiated ``cordic_sincos`` module.
    """

    def __init__(
        self,
        n_oscillators: int,
        bit_width: int = _WORD_BITS,
        cordic_stages: int = 4,
    ) -> None:
        if n_oscillators < 1:
            raise ValueError(f"n_oscillators must be >= 1, got {n_oscillators}")
        if bit_width != _WORD_BITS:
            raise ValueError(
                f"only {_WORD_BITS}-bit Q16.16 is supported, got {bit_width}"
            )
        if cordic_stages < 1:
            raise ValueError(f"cordic_stages must be >= 1, got {cordic_stages}")
        self.n = n_oscillators
        self.width = bit_width
        self.cordic_stages = cordic_stages

    def compile(self, knm: NDArray, omegas: NDArray, dt: float) -> str:
        r"""Generate a synthesisable Verilog module for the mesh.

        The returned string is a complete module suitable for writing to a
        ``.v`` file and feeding to the synthesis step of an FPGA tool.
        The module depends on ``cordic_sincos`` being available on the
        include path (usually via ``\`include "kuramoto_core.v"`` or an
        IP library).
        """
        if knm.shape != (self.n, self.n):
            raise ValueError(
                f"knm shape {knm.shape} does not match n={self.n} oscillators"
            )
        if omegas.shape != (self.n,):
            raise ValueError(
                f"omegas shape {omegas.shape} does not match n={self.n} oscillators"
            )
        if dt <= 0.0:
            raise ValueError(f"dt must be positive, got {dt}")

        dt_q = _hex_q16_16(dt)
        lines: list[str] = []
        lines.append("// Automatically generated by SCPN Phase Orchestrator.")
        lines.append(
            "// Requires cordic_sincos (spo-fpga/kuramoto_core.v) on include path."
        )
        lines.append(f"module kuramoto_mesh_{self.n} #(")
        lines.append(f"    parameter WIDTH = {self.width},")
        lines.append(f"    parameter CORDIC_STAGES = {self.cordic_stages}")
        lines.append(") (")
        lines.append("    input  wire clk,")
        lines.append("    input  wire rst_n,")
        lines.append(f"    output wire signed [WIDTH-1:0] theta_out [0:{self.n - 1}]")
        lines.append(");")
        lines.append(f"    localparam signed [WIDTH-1:0] DT_Q = {dt_q};")

        # Omega constants
        for i in range(self.n):
            lines.append(
                f"    localparam signed [WIDTH-1:0] OMEGA_{i} = "
                f"{_hex_q16_16(float(omegas[i]))};"
            )

        # Non-zero coupling constants (flattened to (i,j) tuples)
        active_edges: list[tuple[int, int, float]] = []
        for i in range(self.n):
            for j in range(self.n):
                if i == j:
                    continue
                k_ij = float(knm[i, j])
                if k_ij == 0.0:
                    continue
                active_edges.append((i, j, k_ij))

        for i, j, k_ij in active_edges:
            lines.append(
                f"    localparam signed [WIDTH-1:0] K_{i}_{j} = "
                f"{_hex_q16_16(k_ij)};"
            )

        # State registers + output wiring
        for i in range(self.n):
            lines.append(f"    reg signed [WIDTH-1:0] theta_{i};")
            lines.append(f"    assign theta_out[{i}] = theta_{i};")

        # CORDIC instances for every active edge
        for i, j, _ in active_edges:
            lines.append(f"    wire signed [WIDTH-1:0] diff_{i}_{j};")
            lines.append(
                f"    assign diff_{i}_{j} = theta_{j} - theta_{i};"
            )
            lines.append(f"    wire signed [WIDTH-1:0] sin_{i}_{j};")
            lines.append(f"    wire signed [WIDTH-1:0] cos_{i}_{j};  // unused")
            lines.append(
                f"    cordic_sincos #(.WIDTH(WIDTH), .STAGES(CORDIC_STAGES)) "
                f"u_cordic_{i}_{j} ("
            )
            lines.append("        .clk(clk),")
            lines.append("        .rst_n(rst_n),")
            lines.append("        .valid_in(1'b1),")
            lines.append(f"        .angle_in(diff_{i}_{j}),")
            lines.append("        .valid_out(/* unused */),")
            lines.append(f"        .sin_out(sin_{i}_{j}),")
            lines.append(f"        .cos_out(cos_{i}_{j})")
            lines.append("    );")

        # Q16.16 multiply helper — combinational widened product + truncation.
        # Each K_ij · sin_ij is computed as a 64-bit product, shifted right
        # by FRAC_BITS to return a Q16.16 value.
        for i, j, _ in active_edges:
            lines.append(f"    wire signed [2*WIDTH-1:0] prod_{i}_{j};")
            lines.append(
                f"    assign prod_{i}_{j} = $signed(K_{i}_{j}) * "
                f"$signed(sin_{i}_{j});"
            )
            lines.append(f"    wire signed [WIDTH-1:0] term_{i}_{j};")
            lines.append(
                f"    assign term_{i}_{j} = "
                f"prod_{i}_{j}[2*WIDTH-1:{_FRAC_BITS}];"
            )

        # Aggregate sum per oscillator (ω_i + Σ_j term_ij)
        for i in range(self.n):
            row_terms = [f"OMEGA_{i}"]
            for e_i, e_j, _ in active_edges:
                if e_i == i:
                    row_terms.append(f"term_{e_i}_{e_j}")
            lines.append(f"    wire signed [WIDTH-1:0] dtheta_{i};")
            lines.append(f"    assign dtheta_{i} = " + " + ".join(row_terms) + ";")
            lines.append(f"    wire signed [2*WIDTH-1:0] dtheta_dt_{i};")
            lines.append(
                f"    assign dtheta_dt_{i} = "
                f"$signed(dtheta_{i}) * $signed(DT_Q);"
            )
            lines.append(f"    wire signed [WIDTH-1:0] dtheta_scaled_{i};")
            lines.append(
                f"    assign dtheta_scaled_{i} = "
                f"dtheta_dt_{i}[2*WIDTH-1:{_FRAC_BITS}];"
            )

        # Sequential Euler update (Q16.16)
        lines.append("    integer reset_i;")
        lines.append("    always @(posedge clk or negedge rst_n) begin")
        lines.append("        if (!rst_n) begin")
        for i in range(self.n):
            lines.append(f"            theta_{i} <= {self.width}'sd0;")
        lines.append("        end else begin")
        for i in range(self.n):
            lines.append(
                f"            theta_{i} <= theta_{i} + dtheta_scaled_{i};"
            )
        lines.append("        end")
        lines.append("    end")
        lines.append("endmodule")

        return "\n".join(lines)
