#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — SPDX header presence gate

"""Fail-closed gate: every tracked Python source carries an SPDX header.

The project rule is a licence header on every source file. This gate enforces the
essential invariant — the ``SPDX-License-Identifier`` line is present at the top
of the file (line 1, or line 2 when line 1 is a shebang) — for every tracked
``*.py`` file, so a new file without a header turns CI red instead of slipping in
silently. Generated sources under ``runtime/grpc_gen/`` are exempt: they are
regenerated by ``tools/generate_grpc.py`` and carry the upstream tool's banner.

The gate checks presence only, not the exact 7-line format, so it never
false-positives on a valid header whose wording differs.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from collections.abc import Iterable, Sequence
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

SPDX_MARKER = "SPDX-License-Identifier"
SHEBANG_PREFIX = "#!"

# Generated sources that carry an upstream banner instead of the project header.
EXEMPT_POSIX_PREFIXES: tuple[str, ...] = (
    "src/scpn_phase_orchestrator/runtime/grpc_gen/",
)


def has_spdx_header(path: Path) -> bool:
    """Return whether ``path`` declares an SPDX identifier in its header.

    Parameters
    ----------
    path : Path
        The Python source file to inspect.

    Returns
    -------
    bool
        ``True`` if the SPDX marker is on line 1, or on line 2 when line 1 is a
        shebang; ``False`` otherwise (including an unreadable or empty file).
    """
    try:
        with path.open(encoding="utf-8") as handle:
            first = handle.readline()
            if SPDX_MARKER in first:
                return True
            if first.startswith(SHEBANG_PREFIX):
                return SPDX_MARKER in handle.readline()
    except (OSError, UnicodeDecodeError):
        return False
    return False


def _is_exempt(posix_path: str) -> bool:
    """Return whether a repo-relative POSIX path is an exempt generated source."""
    return posix_path.startswith(EXEMPT_POSIX_PREFIXES)


def tracked_python_files(root: Path = REPO_ROOT) -> list[Path]:
    """Return the repository's tracked ``*.py`` files in stable order.

    Parameters
    ----------
    root : Path
        The repository root to enumerate.

    Returns
    -------
    list[Path]
        Absolute paths of tracked Python files, sorted.

    Raises
    ------
    RuntimeError
        If the ``git`` executable cannot be located.
    """
    git = shutil.which("git")
    if git is None:
        raise RuntimeError("git executable is required to enumerate tracked files")
    result = subprocess.run(
        [git, "-C", str(root), "ls-files", "--", "*.py"],
        check=True,
        stdout=subprocess.PIPE,
        text=True,
    )
    return sorted(root / line for line in result.stdout.splitlines() if line)


def find_missing(paths: Iterable[Path], *, root: Path = REPO_ROOT) -> list[Path]:
    """Return the non-exempt Python files that lack an SPDX header.

    Parameters
    ----------
    paths : Iterable[Path]
        Candidate Python files.
    root : Path
        Repository root, used to compute exemption paths.

    Returns
    -------
    list[Path]
        Paths with no SPDX header, generated exemptions removed, in input order.
    """
    missing: list[Path] = []
    root_resolved = root.resolve()
    for path in paths:
        try:
            posix = path.resolve().relative_to(root_resolved).as_posix()
        except ValueError:
            # A path outside the repository root is never a generated exemption.
            posix = ""
        if posix and _is_exempt(posix):
            continue
        if not has_spdx_header(path):
            missing.append(path)
    return missing


def _display_path(path: Path) -> str:
    """Return ``path`` repo-relative when under the root, else its absolute form.

    Parameters
    ----------
    path : Path
        The path to render for a violation report.

    Returns
    -------
    str
        A repo-relative POSIX path when ``path`` is inside the repository, the
        absolute path otherwise.
    """
    resolved = path.resolve()
    if resolved.is_relative_to(REPO_ROOT):
        return resolved.relative_to(REPO_ROOT).as_posix()
    return str(resolved)


def main(argv: Sequence[str] | None = None) -> int:
    """Check tracked (or explicitly listed) Python files for SPDX headers.

    Parameters
    ----------
    argv : Sequence[str] | None
        Optional explicit file paths; defaults to every tracked ``*.py``.

    Returns
    -------
    int
        ``0`` if all files carry a header, ``1`` if any is missing one.
    """
    args = list(sys.argv[1:] if argv is None else argv)
    paths = [Path(arg) for arg in args] if args else tracked_python_files()
    missing = find_missing(paths)
    if missing:
        print(f"SPDX header missing from {len(missing)} file(s):", file=sys.stderr)
        for path in missing:
            print(f"  {_display_path(path)}", file=sys.stderr)
        return 1
    print(f"SPDX headers present on all {len(paths)} checked Python file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
