# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Unmasked connectome owner typing

[mypy]
strict = true
explicit_package_bases = true
follow_imports = silent
warn_unused_ignores = true
disallow_any_explicit = true
disallow_any_unimported = true
mypy_path = $MYPY_CONFIG_FILE_DIR/../src, $MYPY_CONFIG_FILE_DIR/..
