# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Julia API documentation renderer

"""Render Julia accelerator modules and their callable signatures as Markdown."""

repo_root = normpath(joinpath(@__DIR__, ".."))
source_root = joinpath(repo_root, "julia")
output_path = if haskey(ENV, "SPO_JULIA_DOC_OUTPUT")
    get(ENV, "SPO_JULIA_DOC_OUTPUT", "")
elseif !isempty(ARGS)
    abspath(ARGS[1])
else
    ""
end
isempty(output_path) && error("output path must be supplied as ARGS[1] or SPO_JULIA_DOC_OUTPUT")

function source_summary(source::String)::String
    block = match(r"\"\"\"\s*(.*?)\s*\"\"\""s, source)
    if block !== nothing
        return strip(block.captures[1])
    end
    for line in eachline(IOBuffer(source))
        if occursin("SCPN Phase Orchestrator", line)
            return strip(replace(line, r"^#\s*" => ""))
        end
    end
    return "Independent Julia accelerator module."
end

function method_doc(mod::Module, symbol::Symbol, method::Method)::String
    binding = Docs.Binding(mod, symbol)
    signature = Base.tuple_type_tail(method.sig)
    try
        doc = Docs.docstr(binding, signature)
        return strip(join(string.(doc.text), "\n"))
    catch error
        error isa ErrorException || rethrow()
        return ""
    end
end

function own_public_methods(mod::Module)
    entries = Pair{Symbol, Vector{Tuple{String, String}}}[]
    for symbol in sort!(collect(names(mod; all = true, imported = false)); by = string)
        name = string(symbol)
        if symbol in (:eval, :include) || startswith(name, "_") || !isdefined(mod, symbol)
            continue
        end
        value = getfield(mod, symbol)
        value isa Function || continue
        signatures = Tuple{String, String}[]
        for method in methods(value)
            method.module === mod || continue
            rendered = first(split(sprint(show, method), " @ "; limit = 2))
            push!(signatures, (rendered, method_doc(mod, symbol, method)))
        end
        isempty(signatures) || push!(entries, symbol => sort!(signatures; by = first))
    end
    return entries
end

mkpath(dirname(output_path))
open(output_path, "w") do io
    println(io, "<!-- SPDX-License-Identifier: AGPL-3.0-or-later -->")
    println(io, "<!-- Generated by tools/generate_julia_docs.jl; do not edit. -->")
    println(io, "# Julia accelerator API")
    println(io)
    println(io, "Generated from the independent modules under `julia/`.")

    for source_path in sort!(readdir(source_root; join = true))
        endswith(source_path, ".jl") || continue
        source = read(source_path, String)
        mod = Base.include(Main, source_path)
        mod isa Module || error("$(basename(source_path)) did not evaluate to a module")
        println(io)
        println(io, "## `", nameof(mod), "`")
        println(io)
        println(io, source_summary(source))
        for (symbol, methods) in own_public_methods(mod)
            println(io)
            println(io, "### `", symbol, "`")
            for (signature, docs) in methods
                println(io)
                println(io, "```julia")
                println(io, signature)
                println(io, "```")
                if !isempty(docs)
                    println(io)
                    println(io, docs)
                end
            end
        end
    end
end
