#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# SCPN Phase Orchestrator — Hash-pinned dependency lock refresh

"""Regenerate every generated hash-pinned lockfile under ``requirements/``.

Each lock is resolved by the generator and interpreter that its committed
header records. ``pip-compile`` locks run through ``uvx`` with the pinned
``pip-tools`` release and the lock's own Python version, so a refresh no
longer depends on whichever ``pip-compile`` happens to be on ``PATH`` or on
the interpreter the caller remembered to select. The Windows FFI locks are
resolved by ``uv pip compile`` for the Windows platform.

``pip-compile`` rewrites the whole output file. A licence block that precedes
its generated header is therefore captured before the run and restored
byte-for-byte afterwards; the tool refuses to overwrite a lock whose regenerated
text does not start with the generator header it expects.

Without ``--upgrade`` existing pins are resolver preferences, so a refresh keeps
every pin that still satisfies the declared inputs. ``--upgrade`` re-resolves
every lock to the newest versions its inputs allow; neither generator records
that flag in the lock header, so the header contract is unchanged. Resolver
caches follow ``PIP_TOOLS_CACHE_DIR`` and ``UV_CACHE_DIR`` from the environment.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

ROOT = Path(__file__).resolve().parent.parent

PIP_TOOLS_VERSION = "7.6.1"
"""pip-tools release used for every ``pip-compile`` lock.

7.5.3 fails against pip 26.2 (``ImportError: stdlib_pkgs``); 7.6.1 is the
first release verified against the pip pinned in the development locks.
"""

PIP_COMPILE_HEADER = "# This file is autogenerated by pip-compile"
UV_HEADER = "# This file was autogenerated by uv"

Generator = Literal["pip-compile", "uv"]

_DEV_EXTRAS = (
    "--extra=dev",
    "--extra=full",
    "--extra=nn",
    "--extra=notebook",
    "--extra=plot",
    "--extra=queuewaves",
)
_HASHED = ("--generate-hashes", "--no-emit-index-url")
_WINDOWS_EXTRAS = (
    "--extra",
    "dev",
    "--extra",
    "full",
    "--extra",
    "nn",
    "--extra",
    "notebook",
    "--extra",
    "plot",
)


@dataclass(frozen=True)
class LockSpec:
    """One generated lockfile and the exact command that produces it.

    Attributes
    ----------
    output : str
        Repository-relative path of the lockfile.
    generator : {"pip-compile", "uv"}
        Resolver that owns the file header.
    python : str
        ``major.minor`` interpreter the lock is resolved for.
    arguments : tuple of str
        Generator arguments after the executable, in header order, including
        the output path and the input file.
    """

    output: str
    generator: Generator
    python: str
    arguments: tuple[str, ...]

    @property
    def name(self) -> str:
        """Return the lockfile name without directory, used by ``--only``."""
        return Path(self.output).name


def _dev_lock(output: str, python: str) -> LockSpec:
    return LockSpec(
        output=output,
        generator="pip-compile",
        python=python,
        arguments=(
            *_DEV_EXTRAS,
            *_HASHED,
            f"--output-file={output}",
            "--strip-extras",
            "pyproject.toml",
        ),
    )


def _windows_lock(output: str, python: str) -> LockSpec:
    return LockSpec(
        output=output,
        generator="uv",
        python=python,
        arguments=(
            "--python-platform",
            "windows",
            "--python-version",
            python,
            *_WINDOWS_EXTRAS,
            *_HASHED,
            "--strip-extras",
            "pyproject.toml",
            "-o",
            output,
        ),
    )


def _input_lock(
    output: str,
    source: str,
    *,
    constrained: bool = False,
    strip_extras: bool = False,
    allow_unsafe: bool = False,
) -> LockSpec:
    arguments: list[str] = []
    if allow_unsafe:
        arguments.append("--allow-unsafe")
    if constrained:
        arguments.append("--constraint=requirements/dev-lock.txt")
    arguments.extend(_HASHED)
    arguments.append(f"--output-file={output}")
    if strip_extras:
        arguments.append("--strip-extras")
    arguments.append(source)
    return LockSpec(
        output=output,
        generator="pip-compile",
        python="3.12",
        arguments=tuple(arguments),
    )


LOCKS: tuple[LockSpec, ...] = (
    _dev_lock("requirements/dev-lock.txt", "3.12"),
    _dev_lock("requirements/dev-lock-py311.txt", "3.11"),
    _dev_lock("requirements/dev-lock-py313.txt", "3.13"),
    _windows_lock("requirements/dev-lock-windows-ffi-py311.txt", "3.11"),
    _windows_lock("requirements/dev-lock-windows-ffi-py312.txt", "3.12"),
    LockSpec(
        output="requirements/runtime-lock.txt",
        generator="pip-compile",
        python="3.12",
        arguments=(
            *_HASHED,
            "--output-file=requirements/runtime-lock.txt",
            "pyproject.toml",
        ),
    ),
    LockSpec(
        output="requirements/queuewaves-lock.txt",
        generator="pip-compile",
        python="3.12",
        arguments=(
            "--extra=queuewaves",
            *_HASHED,
            "--output-file=requirements/queuewaves-lock.txt",
            "--strip-extras",
            "pyproject.toml",
        ),
    ),
    _input_lock(
        "requirements/julia-lock.txt",
        "requirements/julia.in",
        constrained=True,
        strip_extras=True,
    ),
    _input_lock(
        "requirements/mojo-lock.txt",
        "requirements/mojo.in",
        constrained=True,
        strip_extras=True,
    ),
    _input_lock(
        "requirements/studio-sdk.txt",
        "requirements/studio-sdk.in",
        constrained=True,
    ),
    _input_lock("requirements/pqc-lock.txt", "requirements/pqc.in"),
    _input_lock("requirements/precommit-tools.txt", "requirements/precommit-tools.in"),
    _input_lock(
        "requirements/publish-tools.txt",
        "requirements/publish-tools.in",
        strip_extras=True,
    ),
    _input_lock(
        "requirements/audit-tools.txt",
        "requirements/audit-tools.in",
        allow_unsafe=True,
    ),
    _input_lock("requirements/release-tools.txt", "requirements/release-tools.in"),
)
"""Every generated lock, in dependency order.

``dev-lock.txt`` precedes the locks that use it as a ``--constraint``.
``ci-tools.txt`` and ``docs-tools.txt`` are hand-maintained pin lists without a
generator header and are deliberately absent.
"""


def generator_header(generator: Generator) -> str:
    """Return the first header line a generator writes.

    Parameters
    ----------
    generator : {"pip-compile", "uv"}
        Resolver name.

    Returns
    -------
    str
        Header line prefix that identifies the generator.
    """
    return PIP_COMPILE_HEADER if generator == "pip-compile" else UV_HEADER


def preserved_prefix(text: str, generator: Generator) -> str:
    """Return the hand-maintained block that precedes the generator header.

    ``pip-compile`` opens its header with a bare ``#`` line followed by the
    ``This file is autogenerated`` line; ``uv`` opens directly with its line.
    Everything before that opening belongs to the repository and must survive
    a regeneration unchanged.

    Parameters
    ----------
    text : str
        Current lockfile content.
    generator : {"pip-compile", "uv"}
        Resolver that owns the generated part.

    Returns
    -------
    str
        The exact prefix, including its trailing newline, or ``""`` when the
        file starts with the generated header.

    Raises
    ------
    ValueError
        If the generator header is absent, or a ``pip-compile`` header is not
        preceded by its opening ``#`` line.
    """
    lines = text.splitlines(keepends=True)
    marker = generator_header(generator)
    for index, line in enumerate(lines):
        if line.startswith(marker):
            if generator == "uv":
                return "".join(lines[:index])
            if index == 0 or lines[index - 1].rstrip("\r\n") != "#":
                raise ValueError(
                    "pip-compile header is not preceded by its opening '#' line"
                )
            return "".join(lines[: index - 1])
    raise ValueError(f"generator header {marker!r} not found")


def restore_prefix(prefix: str, regenerated: str, generator: Generator) -> str:
    """Prepend a preserved block to freshly generated lock text.

    Parameters
    ----------
    prefix : str
        Block returned by :func:`preserved_prefix` before regeneration.
    regenerated : str
        Complete text the generator wrote.
    generator : {"pip-compile", "uv"}
        Resolver that wrote ``regenerated``.

    Returns
    -------
    str
        ``prefix + regenerated``.

    Raises
    ------
    ValueError
        If ``regenerated`` does not itself begin with the generator header, which
        means the generator did not own the whole file and restoring the prefix
        could duplicate or reorder repository text.
    """
    if preserved_prefix(regenerated, generator):
        raise ValueError("regenerated lock does not start with the generator header")
    return prefix + regenerated


def build_command(
    spec: LockSpec, *, uvx: str, uv: str, upgrade: bool = False
) -> list[str]:
    """Return the argument vector that regenerates ``spec``.

    Parameters
    ----------
    spec : LockSpec
        Lock to regenerate.
    uvx : str
        Absolute path of the ``uvx`` executable.
    uv : str
        Absolute path of the ``uv`` executable.
    upgrade : bool, optional
        Re-resolve every package to the newest version the inputs allow
        instead of keeping existing pins.

    Returns
    -------
    list of str
        Command suitable for :func:`subprocess.run` with ``cwd`` at the
        repository root.
    """
    upgrade_flag = ["--upgrade"] if upgrade else []
    if spec.generator == "uv":
        return [uv, "pip", "compile", *upgrade_flag, *spec.arguments]
    return [
        uvx,
        "--python",
        spec.python,
        "--from",
        f"pip-tools=={PIP_TOOLS_VERSION}",
        "pip-compile",
        *upgrade_flag,
        *spec.arguments,
    ]


def select_locks(names: Sequence[str]) -> tuple[LockSpec, ...]:
    """Return the requested locks in canonical order.

    Parameters
    ----------
    names : sequence of str
        Lockfile names such as ``"dev-lock.txt"``; empty selects every lock.

    Returns
    -------
    tuple of LockSpec
        Selected specifications, ordered as in :data:`LOCKS`.

    Raises
    ------
    ValueError
        If a name does not match any generated lock.
    """
    if not names:
        return LOCKS
    known = {spec.name for spec in LOCKS}
    unknown = sorted(set(names) - known)
    if unknown:
        raise ValueError(f"unknown lockfile(s): {', '.join(unknown)}")
    wanted = set(names)
    return tuple(spec for spec in LOCKS if spec.name in wanted)


Runner = Callable[[list[str], Path], None]


def _run(command: list[str], root: Path) -> None:
    subprocess.run(command, cwd=root, check=True)


def refresh_lock(
    spec: LockSpec,
    root: Path,
    *,
    uvx: str,
    uv: str,
    upgrade: bool = False,
    runner: Runner = _run,
) -> None:
    """Regenerate one lockfile in place and restore its preserved block.

    Parameters
    ----------
    spec : LockSpec
        Lock to regenerate.
    root : pathlib.Path
        Repository root; commands run with this working directory.
    uvx, uv : str
        Absolute executable paths.
    upgrade : bool, optional
        Pass ``--upgrade`` to the generator.
    runner : callable, optional
        Executes a command in ``root``; defaults to :func:`subprocess.run`
        with ``check=True``.

    Raises
    ------
    ValueError
        If the committed or regenerated file lacks the expected header. The
        committed bytes are restored before the error propagates.
    subprocess.CalledProcessError
        If the generator fails. The committed bytes are restored first.
    """
    path = root / spec.output
    original = path.read_text(encoding="utf-8")
    prefix = preserved_prefix(original, spec.generator)
    try:
        runner(build_command(spec, uvx=uvx, uv=uv, upgrade=upgrade), root)
        regenerated = path.read_text(encoding="utf-8")
        path.write_text(
            restore_prefix(prefix, regenerated, spec.generator), encoding="utf-8"
        )
    except BaseException:
        path.write_text(original, encoding="utf-8")
        raise


def _executable(name: str) -> str:
    found = shutil.which(name)
    if found is None:
        raise SystemExit(f"{name} is required on PATH to refresh dependency locks")
    return found


def main(argv: Sequence[str] | None = None) -> int:
    """Run the command-line interface.

    Parameters
    ----------
    argv : sequence of str, optional
        Arguments without the program name; defaults to ``sys.argv[1:]``.

    Returns
    -------
    int
        Process exit status: 0 on success, 2 for an unknown lock name.
    """
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--only",
        action="append",
        default=[],
        metavar="LOCKFILE",
        help="refresh only this lockfile name (repeatable)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the commands without running them",
    )
    parser.add_argument(
        "--upgrade",
        action="store_true",
        help="re-resolve every package to the newest version the inputs allow",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print the generated lockfiles and their interpreters",
    )
    args = parser.parse_args(argv)
    try:
        selected = select_locks(args.only)
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 2
    if args.list:
        for spec in selected:
            print(f"{spec.output}\t{spec.generator}\tpython {spec.python}")
        return 0
    if args.dry_run:
        for spec in selected:
            print(
                " ".join(build_command(spec, uvx="uvx", uv="uv", upgrade=args.upgrade))
            )
        return 0
    uvx = _executable("uvx")
    uv = _executable("uv")
    for spec in selected:
        print(f"refreshing {spec.output} (python {spec.python})", flush=True)
        refresh_lock(spec, ROOT, uvx=uvx, uv=uv, upgrade=args.upgrade)
    return 0


if __name__ == "__main__":
    sys.exit(main())
